baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hits By Hali'
theme = 'mainroad'

[Params.logo]
  image = "/img/haliweblogo.svg"
  title = "Hits By Hali"
  subtitle = "How we're making music"


[Params.style.vars]
  highlightColor = "#0B9DBB"


[params.meta]
  Favicon = true
  svg = true
  
