baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hits By Hali'
theme = 'mainroad'

[Params]
  googleFontsLink = "local"
  post_meta = ["author", "date", "categories", "translations"]
  customCSS = ["css/home.css", "css/gallery.css", "css/links.css", "css/posts.css", "css/mobile-nav.css"]
  mainSections = ["posts"]
  
[Params.menu]
  menu="main"

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  # Enable widgets in given order
  widgets = ["recent-music", "recent","recent-poetry", "categories", "taglist", "social"]
[Params.logo]
  image = "img/haliweblogo.svg"
  title = "Hits By Hali"
  subtitle = "What I've Been Making"


[Params.style.vars]
  highlightColor = "#0B9DBB"
  fontFamilyPrimary = "Charter, 'Bitstream Charter', Georgia, serif"
  


[params.meta]
  Favicon = true
  svg = true
  

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[security]
  enableInlineShortcodes = true

[menus]
  [[menus.main]]
    name = 'Music'
    pageRef = '/music'
    weight = 10
  [[menus.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = 'Gallery'
    pageRef = '/gallery'
    weight = 30
  [[menus.main]]
    name = 'Links'
    pageRef = '/links'
    weight = 50
  # Poetry hidden from nav until ready
  # [[menus.main]]
  #   name = 'Poetry'
  #   pageRef = '/poetry'
  #   weight = 40