baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hits By Hali'
theme = 'mainroad'

[Params]
  # googleFontsLink = "https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap"
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400&display=swap"
  


[Params.logo]
  image = "/img/haliweblogo.svg"
  title = "Hits By Hali"
  subtitle = "How we're making music"


[Params.style.vars]
  highlightColor = "#0B9DBB"
  fontFamilyPrimary = "'Roboto', sans-serif"
  


[params.meta]
  Favicon = true
  svg = true
  

[caches]
  [caches.images]
    dir = ':cacheDir/images'

